### ISSUE TITLE
ChatGPT response is not fully displayed

### ISSUE THREAD

**Issue by Nord1cWarr1or** [kudoai/duckduckgpt#7]
This answer is not shown in its entirety and is even interrupted halfway through the word.

![img](https://github.com/kudoai/duckduckgpt/assets/47604048/499a6338-199a-4ecb-9aaa-ff4385ddaef2)

I'm using firefox based borowser and Tampermonkey. duckduckgpt version is `2023.5.10`

**Comment by adamlui** [comment]
Hey @Nord1cWarr1or nice name and thanks for reporting this. Someone had a similar issue in  https://github.com/adamlui/userscripts/issues/9 which a Chrome auto-update fixed, but you are using FF

Are you using Proxy or regular mode? Is the cut-off msg from a search query or a reply sent by you? Also if you are using unproxied mode, does this cut-off msg show as cut-off or complete in your chat history @ chat.openai.com?

**Comment by Nord1cWarr1or** [comment]
> Are you using Proxy or regular mode? Is the cut-off msg from a search query or a reply sent by you? Also if you are using unproxied mode, does this cut-off msg show as cut-off or complete in your chat history @ chat.openai.com?

I'm using proxy mode. Messages are cut off in all cases, when I search or reply to my message.

**Comment by adamlui** [comment]
@Nord1cWarr1or sorry for the late reply I had not been feeling well. I determined the cause was the proxy API I use cuts off non-English responses for some reason. But if you switch to unproxied mode (requires OpenAI acct) replies will be complete, even in non-English:

![image](https://github.com/kudoai/duckduckgpt/assets/10906554/6b479d89-f1e8-4893-bc01-fcc0bc10a9fa)

If you want to refrain from signing up w/ OpenAI, you can edit line 57...

```js
    var proxyEndpointMap = [[ 'https://c1b9-67-188-52-169.ngrok.io', 'pk-pJNAtlAqCHbUDTrDudubjSKeUVgbOMvkRQWMLtscqsdiKmhI', 'gpt-4' ]]
```
... by replacing `'gpt-4'` with either:
- `alpaca-13b` (open-source LLM based on GPT-3.5 Turbo)
- `vicuna-13b` (open-source LLM based on GPT-4)

Note this will result in drastically slower responses, ~+5sec in my testing

Then when I eventually incorporate a model selector, your script will auto-update and replace your changes

**Comment by Nord1cWarr1or** [comment]
>sorry for the late reply I had not been feeling well. 

Don't worry about it.

>Then when I eventually incorporate a model selector (when I feel better) your script will auto-update and replace your changes

OK, Thank you :)
